// <auto-generated />
namespace secondHandPro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class asdsdsdsd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asdsdsdsd));
        
        string IMigrationMetadata.Id
        {
            get { return "201908112122439_asdsdsdsd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
